### Recipe recommender

In [3]:
import numpy as np 
import pandas as pd

In [4]:
file_path = r'D:\shivam\UKW_work\data\food_com_GeniusKitchen\RAW_recipes.csv'
df = pd.read_csv(file_path)

In [5]:
df=df[['ingredients','name','id','minutes','tags','steps']]
df.head()

,ingredients,name,id,minutes,tags,steps
0,"['winter squash', 'mexican seasoning', 'mixed ...",arriba baked winter squash mexican style,137739,55,"['60-minutes-or-less', 'time-to-make', 'course...","['make a choice and proceed with recipe', 'dep..."
1,"['prepared pizza crust', 'sausage patty', 'egg...",a bit different breakfast pizza,31490,30,"['30-minutes-or-less', 'time-to-make', 'course...","['preheat oven to 425 degrees f', 'press dough..."
2,"['ground beef', 'yellow onions', 'diced tomato...",all in the kitchen chili,112140,130,"['time-to-make', 'course', 'preparation', 'mai...","['brown ground beef in large pot', 'add choppe..."
3,"['spreadable cheese with garlic and herbs', 'n...",alouette potatoes,59389,45,"['60-minutes-or-less', 'time-to-make', 'course...",['place potatoes in a large pot of lightly sal...
4,"['tomato juice', 'apple cider vinegar', 'sugar...",amish tomato ketchup for canning,44061,190,"['weeknight', 'time-to-make', 'course', 'main-...",['mix all ingredients& boil for 2 1 / 2 hours ...

In [6]:
file_path = r'D:\shivam\UKW_work\data\food_com_GeniusKitchen\RAW_interactions.csv'
df_inter = pd.read_csv(file_path)

In [7]:
df_inter.head()

,user_id,recipe_id,date,rating,review
0,38094,40893,2003-02-17,4,Great with a salad. Cooked on top of stove for...
1,1293707,40893,2011-12-21,5,"So simple, so delicious! Great for chilly fall..."
2,8937,44394,2002-12-01,4,This worked very well and is EASY. I used not...
3,126440,85009,2010-02-27,5,I made the Mexican topping and took it to bunk...
4,57222,85009,2011-10-01,5,"Made the cheddar bacon topping, adding a sprin..."

In [23]:
df_inter=df_inter.groupby('recipe_id').agg({'rating':'mean'}).reset_index()

In [24]:
df_merged= pd.merge(df[['ingredients','name','id','minutes','tags','steps']],df_inter,how='left',left_on='id',right_on='recipe_id')

In [25]:
df_merged

,ingredients,name,id,minutes,tags,steps,recipe_id,rating
0,"['winter squash', 'mexican seasoning', 'mixed ...",arriba baked winter squash mexican style,137739,55,"['60-minutes-or-less', 'time-to-make', 'course...","['make a choice and proceed with recipe', 'dep...",137739,5.0
1,"['prepared pizza crust', 'sausage patty', 'egg...",a bit different breakfast pizza,31490,30,"['30-minutes-or-less', 'time-to-make', 'course...","['preheat oven to 425 degrees f', 'press dough...",31490,3.5
2,"['ground beef', 'yellow onions', 'diced tomato...",all in the kitchen chili,112140,130,"['time-to-make', 'course', 'preparation', 'mai...","['brown ground beef in large pot', 'add choppe...",112140,4.0
3,"['spreadable cheese with garlic and herbs', 'n...",alouette potatoes,59389,45,"['60-minutes-or-less', 'time-to-make', 'course...",['place potatoes in a large pot of lightly sal...,59389,4.5
4,"['tomato juice', 'apple cider vinegar', 'sugar...",amish tomato ketchup for canning,44061,190,"['weeknight', 'time-to-make', 'course', 'main-...",['mix all ingredients& boil for 2 1 / 2 hours ...,44061,5.0
...,...,...,...,...,...,...,...,...
231632,"['celery', 'onion', 'green sweet pepper', 'gar...",zydeco soup,486161,60,"['ham', '60-minutes-or-less', 'time-to-make', ...","['heat oil in a 4-quart dutch oven', 'add cele...",486161,5.0
231633,"['paprika', 'salt', 'garlic powder', 'onion po...",zydeco spice mix,493372,5,"['15-minutes-or-less', 'time-to-make', 'course...",['mix all ingredients together thoroughly'],493372,5.0
231634,"['hard-cooked eggs', 'mayonnaise', 'dijon must...",zydeco ya ya deviled eggs,308080,40,"['60-minutes-or-less', 'time-to-make', 'course...","['in a bowl , combine the mashed yolks and may...",308080,5.0
231635,"['butter', 'eagle brand condensed milk', 'ligh...",cookies by design cookies on a stick,298512,29,"['30-minutes-or-less', 'time-to-make', 'course...",['place melted butter in a large mixing bowl a...,298512,1.0
231636,"['granulated sugar', 'shortening', 'eggs', 'fl...",cookies by design sugar shortbread cookies,298509,20,"['30-minutes-or-less', 'time-to-make', 'course...","['whip sugar and shortening in a large bowl , ...",298509,2.0

In [26]:
df_merged.isnull().sum()

ingredients    0
name           1
id             0
minutes        0
tags           0
steps          0
recipe_id      0
rating         0
dtype: int64

In [27]:
df_merged.dropna(subset='name',inplace=True)

In [28]:
df_merged.isnull().sum()

ingredients    0
name           0
id             0
minutes        0
tags           0
steps          0
recipe_id      0
rating         0
dtype: int64

In [29]:
import ast
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [30]:
def parse_ingredients(ingredients_str):
    return ast.literal_eval(ingredients_str)

df_merged['ingredients_list'] = df_merged['ingredients'].apply(parse_ingredients)

In [31]:
def join_ingredients(ingredients):
    return [ingredient.replace(' ', '') for ingredient in ingredients]

df_merged['ingredients_list'] = df_merged['ingredients_list'].apply(join_ingredients)

In [32]:
df_merged['ingredients_str'] = df_merged['ingredients_list'].apply(lambda x: ' '.join(x))

In [33]:
cv = CountVectorizer(max_features=20000,stop_words='english')
vectors= cv.fit_transform(df_merged['ingredients_str'])

In [41]:
def suggest_recipes(user_ingredients):
  input_ingredients_str = ' '.join([ingredient.replace(' ', '') for ingredient in user_ingredients])
  input_vector = cv.transform([input_ingredients_str])
  # Compute cosine similarity between the input vector and recipe vectors
  similarity_scores = cosine_similarity(input_vector, vectors).flatten()
  df_merged['similarity'] = similarity_scores
  top_recipes = df_merged[df_merged.rating>3].nlargest(10, 'similarity')[['name', 'minutes', 'tags', 'steps','rating','similarity']].sort_values(by=['rating'],ascending=False)
  return top_recipes

In [42]:
user_ingredients =['winter squash', 'butter', 'olive oil']
suggested_recipes = suggest_recipes(user_ingredients)
(suggested_recipes)

,name,minutes,tags,steps,rating,similarity
147563,olive oil butter table spread,5,"['15-minutes-or-less', 'time-to-make', 'course...","['beat butter in mixer until soft', 'gradually...",5.000000,0.666667
0,arriba baked winter squash mexican style,55,"['60-minutes-or-less', 'time-to-make', 'course...","['make a choice and proceed with recipe', 'dep...",5.000000,0.654654
115617,joyce s easy dinner party parmesan potatoes,40,"['60-minutes-or-less', 'time-to-make', 'course...","['preheat oven to 425', 'throw oil and butter ...",5.000000,0.577350
77272,easy no salt garlic croutons,23,"['30-minutes-or-less', 'time-to-make', 'course...","['preheat oven to 325f degrees', 'cut bread in...",5.000000,0.577350
78843,ed s homemade microwave buttery popcorn,7,"['15-minutes-or-less', 'time-to-make', 'course...","['pour popcorn in a paper lunch sack', 'add oi...",5.000000,0.577350
98777,grilled corn with roasted garlic butter,95,"['weeknight', 'time-to-make', 'course', 'main-...",['position rack in center of oven and preheat ...,5.000000,0.577350
150944,oven roast greek potatoes,45,"['60-minutes-or-less', 'time-to-make', 'course...","['preheat oven to 350', 'cut potatoes into chu...",4.666667,0.577350
212119,the humble fried egg,5,"['15-minutes-or-less', 'time-to-make', 'course...",['put the butter and olive oil in a non-stick ...,4.500000,0.666667
64930,crispy pan roasted potatoes,45,"['60-minutes-or-less', 'time-to-make', 'course...",['melt butter with oil in a large heavy skille...,4.000000,0.666667
115741,julia child method of preparing garlic,35,"['60-minutes-or-less', 'time-to-make', 'course...",['remove all the cloves of garlic from the hea...,4.000000,0.577350